### ISSUE TITLE
TypeError: ScatterEOS is not a constructor

### ISSUE THREAD

**Issue by Zhucola** [GetScatter/scatter-js#61]
my nodejs can use "import ... from"
```
var ScatterJS = require("scatterjs-core");
var ScatterEOS = require("scatterjs-plugin-eosjs");
// Don't forget to tell ScatterJS which plugins you are using.
var a = new ScatterEOS();
```
throw 
```
var a = new ScatterEOS();
        ^

TypeError: ScatterEOS is not a constructor
    at Object.<anonymous> (/root/node-v10.13.0-linux-x64/bin/a.js:6:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

use https://get-scatter.com/docs/setting-up-for-web-apps methods
```
npm i -S scatterjs-core
npm i -S scatterjs-plugin-eosjs
npm i -D @babel/runtime

import ScatterJS from 'scatterjs-core';
import ScatterEOS from 'scatterjs-plugin-eosjs';

// Don't forget to tell ScatterJS which plugins you are using.
ScatterJS.plugins( new ScatterEOS() );
```

throw

```
(function (exports, require, module, __filename, __dirname) { import ScatterJS from 'scatterjs-core';
```

how can I use Scatter-js????

thanks

**Comment by nsjames** [comment]
Maybe `require("scatterjs-plugin-eosjs").default`?

**Comment by Zhucola** [comment]
```
var ScatterJS  = require('scatterjs-core');
var ScatterEOS = require('scatterjs-plugin-eosjs');
ScatterJS.plugins( new ScatterEOS() );
```

```
node scatter_test.js
```

throw err
```
ScatterJS.plugins( new ScatterEOS() );
                   ^

TypeError: ScatterEOS is not a constructor
    at Object.<anonymous> (/root/node-v10.13.0-linux-x64/bin/a.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

in your README.md demo，which language use "import ScatterJS from 'scatterjs-core'"  ??? is not nodejs???

thank you!

**Comment by nsjames** [comment]
Please try using `require("scatterjs-plugin-eosjs").default` and not just `require("scatterjs-plugin-eosjs")`

The language is Javascript, using es6 features such as `import` which comes standard in every framework nowadays. What framework are you using?

If this is just a normal node project with no framework then you should be able to just do `require("scatterjs-plugin-eosjs")` but it might require the `.default` property at the end of it.
